name: lighthouse staging
on:
  push:
    branches:
      - feature/lighthouse_audit

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Audit live URL
        uses: jakejarvis/lighthouse-action@master
        with:
          url: "https://techlabs-staging.netlify.app"
      - name: Upload results as an artifact
        uses: actions/upload-artifact@master
        with:
          name: report
          path: "./report"
